### ISSUE TITLE
silent failure

### ISSUE THREAD

**Issue by leagleag** [jhhung/EARRINGS#6]
Hello,

Thank you for developing EARRINGS.

I would like to report a behavior whose cause I cannot trace back.
It can be reproduced by obtaining paired end data from the sample SRR4344089.

`fasterq-dump SRR4344089 --threads 10 --progress --split-3 --outdir <OUTDIR>`

The following command: `EARRINGS paired --input1 SRR4344089_1.fastq.gz --input2 SRR4344089_2.fastq.gz --output out --thread 8 --min_length 101` yields two files out_1.fastq and out_2.fastq.

First the line counts:
SRR4344089_1.fastq.gz - 64945820
SRR4344089_2.fastq.gz - 64945820
out_1.fastq - 98172
out_2.fastq - 95429

Second out_2.fastq appears to be abruptly cut:
> tail -n 2 out_2.fastq
```@SRR4344089.23890 HWI-ST261:603:C6Y3TACXX:4:1101:12771:16990 length=101
GGATTCTTTATTTTTATTTT```

Earrings do not return any errors. What do you think?

Thanks

**Comment by leagleag** [comment]
This happens since earrings is writing to /tmp and when the size is limited no error is actually caught. Would be nice to raise it.
Thanks

**Comment by joyeli** [comment]
We've been investigating this issue for several days but haven't been able to reproduce it. It turns out that our tmp has 120GB, and we completely overlooked the possibility that insufficient tmp space could be causing the problem. We have already added an error message according to the original issue reported, d99f5f3. Thank you.
